#!/usr/bin/env bash

# Set the input field separator to a colon
IFS=":"

# Open the /etc/passwd file for reading
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY COMMAND_SHELL; do
    # Print the formatted output
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < /etc/passwd

