#!/usr/bin/env bash
#comm
hour=0

while [ $hour -lt 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -lt 60 ]
  do
    echo $minute
    minute=$((minute+1))
  done
  hour=$((hour+1))
done
echo "Hour: 12"
minute=1
while [ $minute -lt 60 ]
do
  echo $minute
  minute=$((minute+1))
done

